// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  targetKind: __t.string(),
  targetId: __t.u64(),
  effectId: __t.u64(),
  paramKey: __t.string(),
  label: __t.string(),
  minValue: __t.f64(),
  maxValue: __t.f64(),
  scale: __t.string(),
  color: __t.string(),
};
