// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  owner: __t.identity(),
  clientUploadKey: __t.string().name("client_upload_key"),
  name: __t.string(),
  mimeType: __t.string().name("mime_type"),
  byteSize: __t.u64().name("byte_size"),
  durationMicros: __t.u64().name("duration_micros"),
  sampleRate: __t.u32().name("sample_rate"),
  channels: __t.u32(),
  waveformJson: __t.string().name("waveform_json"),
  createdAt: __t.timestamp().name("created_at"),
});
