// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  targetKind: __t.string().name("target_kind"),
  targetId: __t.u64().name("target_id"),
  effectId: __t.u64().name("effect_id"),
  paramKey: __t.string().name("param_key"),
  label: __t.string(),
  enabled: __t.bool(),
  visible: __t.bool(),
  minValue: __t.f64().name("min_value"),
  maxValue: __t.f64().name("max_value"),
  scale: __t.string(),
  color: __t.string(),
  position: __t.u32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
