// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  trackId: __t.u64().name("track_id"),
  kind: __t.string(),
  name: __t.string(),
  instrumentKind: __t.string().name("instrument_kind"),
  instrumentKey: __t.string().name("instrument_key"),
  assetId: __t.u64().name("asset_id"),
  startBeat: __t.f64().name("start_beat"),
  lengthBeats: __t.f64().name("length_beats"),
  assetOffsetMicros: __t.u64().name("asset_offset_micros"),
  assetDurationMicros: __t.u64().name("asset_duration_micros"),
  gain: __t.f64(),
  fadeInMicros: __t.u64().name("fade_in_micros"),
  fadeOutMicros: __t.u64().name("fade_out_micros"),
  reverse: __t.bool(),
  pitchSemitones: __t.f64().name("pitch_semitones"),
  timeStretch: __t.f64().name("time_stretch"),
  midiJson: __t.string().name("midi_json"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
