// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomId: __t.u64(),
  clientUploadKey: __t.string(),
  name: __t.string(),
  mimeType: __t.string(),
  byteSize: __t.u64(),
  durationMicros: __t.u64(),
  sampleRate: __t.u32(),
  channels: __t.u32(),
  waveformJson: __t.string(),
};
