// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Asset = __t.object("Asset", {
  id: __t.u64(),
  roomId: __t.u64(),
  owner: __t.identity(),
  clientUploadKey: __t.string(),
  name: __t.string(),
  mimeType: __t.string(),
  byteSize: __t.u64(),
  durationMicros: __t.u64(),
  sampleRate: __t.u32(),
  channels: __t.u32(),
  waveformJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type Asset = __Infer<typeof Asset>;

export const AssetChunk = __t.object("AssetChunk", {
  id: __t.u64(),
  assetId: __t.u64(),
  chunkIndex: __t.u32(),
  dataBase64: __t.string(),
  byteSize: __t.u32(),
});
export type AssetChunk = __Infer<typeof AssetChunk>;

export const AutomationLane = __t.object("AutomationLane", {
  id: __t.u64(),
  targetKind: __t.string(),
  targetId: __t.u64(),
  effectId: __t.u64(),
  paramKey: __t.string(),
  label: __t.string(),
  enabled: __t.bool(),
  visible: __t.bool(),
  minValue: __t.f64(),
  maxValue: __t.f64(),
  scale: __t.string(),
  color: __t.string(),
  position: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type AutomationLane = __Infer<typeof AutomationLane>;

export const AutomationPoint = __t.object("AutomationPoint", {
  id: __t.u64(),
  laneId: __t.u64(),
  beat: __t.f64(),
  value: __t.f64(),
  curve: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AutomationPoint = __Infer<typeof AutomationPoint>;

export const Block = __t.object("Block", {
  id: __t.u64(),
  trackId: __t.u64(),
  kind: __t.string(),
  name: __t.string(),
  instrumentKind: __t.string(),
  instrumentKey: __t.string(),
  assetId: __t.u64(),
  startBeat: __t.f64(),
  lengthBeats: __t.f64(),
  loopBeats: __t.f64(),
  assetOffsetMicros: __t.u64(),
  assetDurationMicros: __t.u64(),
  gain: __t.f64(),
  fadeInMicros: __t.u64(),
  fadeOutMicros: __t.u64(),
  reverse: __t.bool(),
  pitchSemitones: __t.f64(),
  timeStretch: __t.f64(),
  midiJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Block = __Infer<typeof Block>;

export const Effect = __t.object("Effect", {
  id: __t.u64(),
  targetKind: __t.string(),
  targetId: __t.u64(),
  kind: __t.string(),
  name: __t.string(),
  enabled: __t.bool(),
  position: __t.u32(),
  paramsJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Effect = __Infer<typeof Effect>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  token: __t.string(),
  name: __t.string(),
  owner: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const RoomMember = __t.object("RoomMember", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  role: __t.string(),
  active: __t.bool(),
  joinedAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
});
export type RoomMember = __Infer<typeof RoomMember>;

export const Track = __t.object("Track", {
  id: __t.u64(),
  roomId: __t.u64(),
  name: __t.string(),
  position: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Track = __Infer<typeof Track>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
});
export type User = __Infer<typeof User>;

export const View = __t.object("View", {
  id: __t.u64(),
  roomId: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  kind: __t.string(),
  locked: __t.bool(),
  isDefault: __t.bool(),
  playState: __t.string(),
  playheadMicros: __t.u64(),
  bpm: __t.u32(),
  beatsPerBar: __t.u32(),
  zoom: __t.u32(),
  scrollLeft: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  loopStartBeat: __t.f64(),
  loopLengthBeats: __t.f64(),
});
export type View = __Infer<typeof View>;

export const ViewTrackState = __t.object("ViewTrackState", {
  id: __t.u64(),
  viewId: __t.u64(),
  trackId: __t.u64(),
  muted: __t.bool(),
  solo: __t.bool(),
  volume: __t.f64(),
  pan: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type ViewTrackState = __Infer<typeof ViewTrackState>;

