// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  blockId: __t.u64(),
  name: __t.string(),
  startBeat: __t.f64(),
  lengthBeats: __t.f64(),
  assetOffsetMicros: __t.u64(),
  assetDurationMicros: __t.u64(),
  gain: __t.f64(),
  fadeInMicros: __t.u64(),
  fadeOutMicros: __t.u64(),
  reverse: __t.bool(),
  pitchSemitones: __t.f64(),
  timeStretch: __t.f64(),
  midiJson: __t.string(),
  instrumentKind: __t.string(),
  instrumentKey: __t.string(),
};
