// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  viewId: __t.u64().name("view_id"),
  trackId: __t.u64().name("track_id"),
  muted: __t.bool(),
  solo: __t.bool(),
  volume: __t.f64(),
  pan: __t.f64(),
  updatedAt: __t.timestamp().name("updated_at"),
});
