// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  owner: __t.identity(),
  name: __t.string(),
  kind: __t.string(),
  locked: __t.bool(),
  isDefault: __t.bool().name("is_default"),
  playState: __t.string().name("play_state"),
  playheadMicros: __t.u64().name("playhead_micros"),
  bpm: __t.u32(),
  beatsPerBar: __t.u32().name("beats_per_bar"),
  zoom: __t.u32(),
  scrollLeft: __t.u32().name("scroll_left"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
