// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAssetChunkReducer from "../add_asset_chunk_reducer";
import AddAutomationLaneReducer from "../add_automation_lane_reducer";
import AddEffectReducer from "../add_effect_reducer";
import CreateAssetReducer from "../create_asset_reducer";
import CreateBlockReducer from "../create_block_reducer";
import CreateRoomReducer from "../create_room_reducer";
import CreateSharedViewReducer from "../create_shared_view_reducer";
import CreateTrackReducer from "../create_track_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import JoinRoomReducer from "../join_room_reducer";
import RegisterUserReducer from "../register_user_reducer";
import RenameTrackReducer from "../rename_track_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import UpdateBlockReducer from "../update_block_reducer";
import UpdateBlockMidiReducer from "../update_block_midi_reducer";
import UpdateViewLayoutReducer from "../update_view_layout_reducer";
import UpdateViewLoopRegionReducer from "../update_view_loop_region_reducer";
import UpdateViewTrackStateReducer from "../update_view_track_state_reducer";
import UpdateViewTransportReducer from "../update_view_transport_reducer";
import UpsertAutomationPointReducer from "../upsert_automation_point_reducer";

export type AddAssetChunkParams = __Infer<typeof AddAssetChunkReducer>;
export type AddAutomationLaneParams = __Infer<typeof AddAutomationLaneReducer>;
export type AddEffectParams = __Infer<typeof AddEffectReducer>;
export type CreateAssetParams = __Infer<typeof CreateAssetReducer>;
export type CreateBlockParams = __Infer<typeof CreateBlockReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type CreateSharedViewParams = __Infer<typeof CreateSharedViewReducer>;
export type CreateTrackParams = __Infer<typeof CreateTrackReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type RenameTrackParams = __Infer<typeof RenameTrackReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type UpdateBlockParams = __Infer<typeof UpdateBlockReducer>;
export type UpdateBlockMidiParams = __Infer<typeof UpdateBlockMidiReducer>;
export type UpdateViewLayoutParams = __Infer<typeof UpdateViewLayoutReducer>;
export type UpdateViewLoopRegionParams = __Infer<typeof UpdateViewLoopRegionReducer>;
export type UpdateViewTrackStateParams = __Infer<typeof UpdateViewTrackStateReducer>;
export type UpdateViewTransportParams = __Infer<typeof UpdateViewTransportReducer>;
export type UpsertAutomationPointParams = __Infer<typeof UpsertAutomationPointReducer>;

